FROM nvidia/cuda:12.2.0-base-ubuntu22.04

# For the installation of tkinter
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich

RUN apt-get update
RUN apt-get install -y sudo gcc make wget curl git nano redis
RUN apt-get install -y python3.10 python3-pip python3.10-venv python3.10-tk
RUN apt-get install -y unzip

# INSTALL CONDA
# ============================================================================================

RUN apt-get update && \
    apt-get install -y dpkg-dev g++ gcc libc6-dev libc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda init bash
